# Generated by Django 2.1.2 on 2022-02-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220221_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
